routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');
Route::get('/apply', 'FrontController@apply');
Route::get('/generate_token', function(){
    $api_token = Str::random(60);
    return $api_token;
});
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
Route::namespace('Panel')->prefix('panel')->name('panel.')->group(function() {
    Route::middleware('can:manage-admin')->prefix('admin')->name('admin.')->group(function() {
        Route::get('/', 'AdminController@dashboard')->name('dashboard');
        Route::get('/messaging', 'AdminController@messaging')->name('messaging');
        Route::post('/sms/send', 'AdminController@send_sms')->name('send_sms');
        Route::get('/school_year', 'AdminController@school_year')->name('school_year');
        Route::get('/setup', 'AdminController@setup')->name('setup');
        Route::get('/logs', 'AdminController@logs')->name('logs');
        Route::post('/setup/save', 'AdminController@save_setup')->name('save_setup');
        Route::post('/setup/save_attendance_setup', 'AdminController@save_attendance_setup')->name('save_attendance_setup');
        Route::post('/school_year/add', 'SchoolYearController@school_year_add')->name('school_year_add');
        Route::post('/school_year/modify', 'SchoolYearController@school_year_modify')->name('school_year_modify');
        Route::post('/school_year/update', 'SchoolYearController@school_year_update')->name('school_year_update');

        Route::get('/courses', 'AdminController@courses')->name('courses');
        Route::post('/course/add', 'CourseController@course_add')->name('course_add');
        Route::post('/course/modify', 'CourseController@course_modify')->name('course_modify');
        Route::post('/course/update', 'CourseController@course_update')->name('course_update');

        Route::get('/events', 'AdminController@events')->name('events');
        Route::post('/event/add', 'EventController@event_add')->name('event_add');
        Route::post('/event/modify', 'EventController@event_modify')->name('event_modify');
        Route::post('/event/update', 'EventController@event_update')->name('event_update');

        Route::get('/students', 'AdminController@students')->name('students');
        Route::get('/students/search_section', 'StudentController@students_search_section')->name('students_search_section');
        Route::post('/student/add', 'StudentController@student_add')->name('student_add');
        Route::post('/student/modify', 'StudentController@student_modify')->name('student_modify');
        Route::post('/student/update', 'StudentController@student_update')->name('student_update');
        Route::post('/student/filter', 'StudentController@filter_students')->name('filter_students');
        
        Route::get('/users', 'AdminController@users')->name('subscribers');
        Route::get('/users/{user_id}', 'UserController@edit_user')->name('edit_user');  
        Route::post('/users/update', 'UserController@update_user')->name('update_user');  
        Route::post('/users/modify', 'UserController@modify_user')->name('modify_user');  
        Route::post('/users/add', 'UserController@add_user')->name('add_user');  

        Route::get('/gate_attendance', 'AdminController@gate_attendance')->name('gate_attendance');
        Route::post('/gate_attendance', 'AdminController@gate_attendance')->name('history_gate_attendance');
    });
});
Route::namespace('Panel')->prefix('panel')->name('panel.')->group(function() {
    Route::middleware('can:manage-student')->prefix('student')->name('student.')->group(function() {
        Route::get('/', 'StudentPanelController@dashboard')->name('dashboard');
        Route::get('/schedules', 'StudentPanelController@schedules')->name('schedules');
        Route::post('/enroll', 'StudentPanelController@process_enroll')->name('process_enroll');
        Route::get('/attendance', 'StudentPanelController@attendance')->name('attendance');
        Route::get('/attendance/view/{schedule_id}', 'StudentPanelController@view_attendance')->name('view_attendance');
        Route::post('/check/present', 'StudentPanelController@check_present')->name('check_present');
    });
});


require __DIR__.'/auth.php';

app/Http/Controllers/Panel/AdminController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Attendance;
use App\Models\Message;
use App\Models\User;
use App\Models\Role;
use App\Models\Course;
use App\Models\Event;
use App\Models\Section;
use App\Models\Setting;
use App\Models\Student;
use App\Models\Gate_attendance;
use App\Models\Attendance_setup;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;

class AdminController extends Controller
{
    //
    public function dashboard(){
        $page_name = 'Dashboard';
        $students = Student::where('status', 'active')->count();
       
        $today = date('Y-m-d');
        return view('panel.admin.dashboard',compact('page_name', 'students'));
    }

    public function logs(){
        $page_name = 'Dashboard';
        $gate_logged = Gate_attendance::with('student')->latest()->take(10)->get();
        $students = Student::where('status', 'active')->count();
        $male_students = Student::where('gender', 'MALE')->where('status', 'active')->count();
        $female_students = Student::where('gender', 'FEMALE')->where('status', 'active')->count();
        $grade11_students = Student::where('grade_year', 'Grade-11')->where('status', 'active')->count();
        $grade12_students = Student::where('grade_year', 'Grade-12')->where('status', 'active')->count();
        $today = date('Y-m-d');
        $gate_logged_count = Gate_attendance::where('date_log', $today)->with('student')->count();
        $gate_logged_count = Gate_attendance::where('date_log', $today)->with('student')->count();
        return view('panel.admin.logs',compact('page_name', 'gate_logged', 'students', 'gate_logged_count', 'male_students', 'female_students', 'grade11_students', 'grade12_students'));
    }

    public function users(){
        $page_name = 'Users';
        $users = User::with('roles')->paginate(10);
        $roles = Role::where('name', '!=', 'member')->get();
        return view('panel.admin.users',compact('page_name', 'users', 'roles'));
    }

    public function messaging(){
        $page_name = 'Messaging';
        $messages = Message::latest()->get();
        return view('panel.admin.messaging',compact('page_name', 'page_name', 'messages'));
    }
    public function send_sms(Request $req){
        $message = new Message();
        $message->message_type = $req->reciever;
        $message->subject = 'n/a';
        $message->message = $req->sms_message;
        $message->status = 'sent';
        $message->save();

        if($req->reciever == 'teacher'){
            $teachers = Teacher::where('status', 'active')->get();
            foreach($teachers as $teacher){
                $ch = curl_init();
                $parameters = array(
                    'apikey' => '9300a37518f74a9d8be83c721c0719a6', //Your API KEY
                    'number' => $teacher->contact_number,
                    'message' => $req->sms_message,
                    'sendername' => 'AZWAYPH'
                );
                curl_setopt( $ch, CURLOPT_URL,'https://semaphore.co/api/v4/messages' );
                curl_setopt( $ch, CURLOPT_POST, 1 );
    
                //Send the parameters set above with the request
                curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query( $parameters ) );
    
                // Receive response from server
                curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
                $output = curl_exec( $ch );
                curl_close ($ch);
            }
            return redirect()->back()->with('success', 'Message successfully sent...');
        }
        else if($req->reciever == 'student'){
            $students = Student::where('status', 'active')->get();
            foreach($students as $student){
                $ch = curl_init();
                $parameters = array(
                    'apikey' => '9300a37518f74a9d8be83c721c0719a6', //Your API KEY
                    'number' => $student->contact_number,
                    'message' => $req->sms_message,
                    'sendername' => 'AZWAYPH'
                );
                curl_setopt( $ch, CURLOPT_URL,'https://semaphore.co/api/v4/messages' );
                curl_setopt( $ch, CURLOPT_POST, 1 );
    
                //Send the parameters set above with the request
                curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query( $parameters ) );
    
                // Receive response from server
                curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
                $output = curl_exec( $ch );
                curl_close ($ch);
            }
            return redirect()->back()->with('success', 'Message successfully sent...');
        }
        else {
            return redirect()->back()->with('success', 'Something is wrong, please retry');
        }
        
    }
    public function school_year(){
        $page_name = 'School Year';
        $school_years = School_year::all();
        return view('panel.admin.school_year',compact('page_name', 'school_years'));
    }

    public function students(){
        $page_name = 'Students';
        $students = Student::latest()->get();
        $courses = Course::where('status', 'active')->get();
        return view('panel.admin.students',compact('page_name', 'students', 'courses'));
    }
    public function courses(){
        $page_name = 'Courses';
        $courses = Course::get();
        return view('panel.admin.courses',compact('page_name', 'courses'));
    }
    public function events(){
        $page_name = 'Events';
        $events = Event::get();
        return view('panel.admin.events',compact('page_name', 'events'));
    }
    public function setup(){
        $settings = Setting::first();
        $attendance_setups = Attendance_setup::first();
        $page_name = 'Setup';
        return view('panel.admin.setup',compact('page_name', 'settings', 'attendance_setups'));
    }
    public function save_setup(Request $req){
        //dd($req);
        $data = Setting::find($req->setting_id);
        $data->am_log_in_time = $req->am_log_in_time;
        $data->am_log_out_time = $req->am_log_out_time;
        $data->pm_log_in_time = $req->pm_log_in_time;
        $data->pm_log_out_time= $req->pm_log_out_time;
        $data->subject_late_time = $req->subject_late_time;
        $data->sms = $req->sms;
        $data->system_date = $req->system_date;
        $data->use_system_date = $req->use_system_date;
        $data->save();
        return redirect()->back()->with('success','Setup updated...');
    }

    public function save_attendance_setup(Request $req){
        //dd($req);
        $data = Attendance_setup::find($req->school_setting_id);
        $data->school_name = $req->school_name;
        $data->school_id = $req->school_id;
        $data->district = $req->district;
        $data->division= $req->division;
        $data->region = $req->region;
        $data->save();
        return redirect()->back()->with('success_attendance_setting','School setting updated');
    }
    public function gate_attendance(Request $req){
        
        
        $page_name = 'Attendance';
        if(isset($req->date_log)){
            $today = $req->date_log;
        }
        else {
            $today = date('Y-m-d');
        }
        //$today = '2021-05-01';
        
        //$gate_attendances = Gate_attendance::where('date_log', $today)->paginate(200);
        $students = Student::where('status', 'active')
        ->with(['student_am_login' => function($query) use ($today){
            $query->where('log_type', 'am-login');
            $query->where('date_log', $today);
        }])
        ->with(['student_am_logout' => function($query) use ($today){
            $query->where('log_type', 'am-logout');
            $query->where('date_log', $today);
        }])
        ->with(['student_pm_login' => function($query) use ($today){
            $query->where('log_type', 'pm-login');
            $query->where('date_log', $today);
        }])
        ->with(['student_pm_logout' => function($query) use ($today){
            $query->where('log_type', 'pm-logout');
            $query->where('date_log', $today);
        }])
        ->paginate(200);
        //dd($students);
        return view ('panel.admin.gate-attendance', compact('page_name', 'today', 'students'));
    }
}

app/Http/Controllers/Panel/CourseController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Course;
use Response;
use Validator;


class CourseController extends Controller
{
    //
    public function course_add(Request $req)
    {
        // Validate the input data
        $validator = Validator::make($req->all(), [
            'course_name' => 'required',
            'course_code' => 'required'
        ]);

        // Check if validation fails
        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'errors' => $validator->errors()->toArray()
            ], 400);
        }

        // Create a new instance of the Course model
        $course = new Course();

        // Set the properties of the new course using the input data
        $course->course_name = $req->course_name;
        $course->course_code = $req->course_code;
        $course->status = 'active';

        // Save the new course to the database
        $course->save();

        // Return the new course
        return response()->json($course, 201);
    }

    public function course_modify(Request $req)
    {
        // Find the course in the database based on the provided course ID
        $course = Course::find($req->course_id);

        // Check if the course exists
        if (!$course) {
            return response()->json(['error' => 'Course not found'], 404);
        }

        // Update the status of the course
        $course->status = $req->course_status;

        // Save the modified course to the database
        $course->save();

        // Return a JSON response containing the modified course data
        return response()->json($course);
    }

    public function course_update(Request $req)
    {
        // Validate the input data
        $validator = Validator::make($req->all(), [
            'course_name' => 'required',
            'course_code' => 'required'
        ]);

        // Check if validation fails
        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'errors' => $validator->errors()
            ], 400);
        }

        // Find the course in the database
        $course = Course::find($req->course_id);

        // Check if the course exists
        if (!$course) {
            return response()->json([
                'success' => false,
                'errors' => ['Course not found']
            ], 404);
        }

        // Update the course properties
        $course->course_name = $req->course_name;
        $course->course_code = $req->course_code;
        $course->save();

        // Return the updated course data
        return response()->json($course);
    }
}

app/Http/Controllers/Panel/SettingController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

use App\Models\Setting;
class SettingController extends Controller
{
    //
    public function save_settings(Request $req){
        dd($req);
        $update_setting = Setting::where('id', '=', 1)->update(['send_bill_day' => $req->send_bill_day, 'send_bill_due_day' => $req->send_bill_due_day, 'notice_day' => $req->notice_day, 'penalty' => $req->penalty, 'sms' => $req->sms]);
            return redirect()->back()->with('success','Settings successfully updated!');
    }
}

resources/views/panel/admin/logs.blade.php
@extends('layouts.panel')
@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">				
	<!--begin::Entry-->
	<div class="d-flex flex-column-fluid">
		<!--begin::Container-->
		<div class="container">
			<!--begin::Dashboard-->
			<div class="row">
				<div class="col-lg-7">
					<!--begin::Base Table Widget 10-->
					<div class="card card-custom gutter-b">
						<!--begin::Header-->
						<div class="card-header border-0 pt-5">
							<h3 class="card-title align-items-start flex-column">
								<span class="card-label font-weight-bolder text-dark">Recent Activities</span>
								<span class="text-muted mt-3 font-weight-bold font-size-sm">Login / Logout of Students
								</span>
							</h3>
						</div>
						<!--end::Header-->
						<!--begin::Body-->
						<div class="card-body pt-2 pb-0 mt-n3">
						<table class="table table-head-custom table-head-bg table-borderless table-vertical-center" id="LoggedTable">
							<thead>
								<tr class="text-left text-uppercase">
									<th style="" class="pl-7">
										<span class="text-dark-75">Name</span>
									</th>
									<th>Date</th>
									<th>Time Log</th>
									<th>Log Type</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>	
								@foreach($gate_logged as $logged)
									<tr>
										<td>{{$logged->student->first_name}} {{$logged->student->last_name}}</td>
										<td>{{$logged->created_at->format('d-M-Y')}}</td>
										<td>{{$logged->time_log}}</td>
										<td>{{$logged->log_type}}</td>
										<td>{{$logged->status}}</td>
									</tr>
								@endforeach
							</tbody>
						</table>
						</div>
						<!--end::Body-->
					</div>
					<!--end::Base Table Widget 10-->
					
				</div>
			</div>
			<!--end::Dashboard-->
		</div>
		<!--end::Container-->
	</div>
	<!--end::Entry-->
</div>
@endsection

resources/views/panel/admin/setup.blade.php
@extends('layouts.panel')
@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">				
	<!--begin::Entry-->
	<div class="d-flex flex-column-fluid">
		<!--begin::Container-->
		<div class="container">
			<!--begin::Dashboard-->
			
			<!--begin::Row-->
			<div class="row">
				<div class="col-lg-12">
			
					<!--begin::Advance Table Widget 4-->
					<div class="card card-custom card-stretch gutter-b">
						<!--begin::Header-->
						
						<div class="card-header border-0 py-5">
							<h3 class="card-title align-items-start flex-column">
								<span class="card-label font-weight-bolder text-dark">Settings</span>
								<span class="text-muted mt-3 font-weight-bold font-size-sm">ANHS-SOA Setups.</span>
							</h3>
							
						</div>
						<!--end::Header-->
						<!--begin::Body-->
						<div class="card-body pt-0 pb-3">
						@if(session('success'))
					        <div class="alert alert-success" role="alert">
					            {{ session('success') }}     
					        </div>
					    @endif
							<form class="form" action="{{route('panel.admin.save_setup')}}" method="post">
								@csrf
								<div class="card-body">
								
									<div class="form-group row">
										<div class="col-lg-3">
											<label>AM Login Time:</label>
											<input type="time" name="am_log_in_time" class="form-control" value="{{$settings->am_log_in_time}}">
											<span class="form-text text-muted">AM Login Time</span>
										</div>
										<div class="col-lg-3">
											<label>AM Logout Time:</label>
											<input type="time" name="am_log_out_time" class="form-control" value="{{$settings->am_log_out_time}}">
											<span class="form-text text-muted">AM Logout Time</span>
										</div>
										<div class="col-lg-3">
											<label>PM Login Time:</label>
											<input type="time" name="pm_log_in_time" class="form-control" value="{{$settings->pm_log_in_time}}">
											<span class="form-text text-muted">PM Login Time</span>
										</div>
										
										<div class="col-lg-3">
											<label>PM Logout Time:</label>
											<input type="time" name="pm_log_out_time" class="form-control" value="{{$settings->pm_log_out_time}}">
											<span class="form-text text-muted">PM Logout Time</span>
										</div>
										
									</div>
									<div class="form-group row">
										<div class="col-lg-3">
											<label>Subject Late Time:</label>
											<input type="number" name="subject_late_time" class="form-control" value="{{$settings->subject_late_time}}">
											<span class="form-text text-muted">Subject Late Time (Minutes)</span>
										</div>
										<div class="col-lg-3">
											<label>System Date:</label>
											<input type="date" name="system_date" class="form-control" value="{{$settings->system_date}}">
											<span class="form-text text-muted">Subject Late Time (Minutes)</span>
										</div>
										<div class="col-lg-3">
											<label>Use system date?</label>
											<select name="use_system_date" id="use_system_date" class="form-control form-control-solid">
											<option value="{{$settings->use_system_date}}">{{ucfirst($settings->use_system_date)}}</option>
											<option value="yes">Yes</option>
											<option value="no">No</option>
											</select>
											<span class="form-text text-muted">This will enable sms feature in the system</span>
										</div>
										<div class="col-lg-3">
											<label>Enable SMS?</label>
											<select name="sms" id="sms" class="form-control form-control-solid">
											<option value="{{$settings->sms}}">{{ucfirst($settings->sms)}}</option>
											<option value="yes">Yes</option>
											<option value="no">No</option>
											</select>
											<span class="form-text text-muted">This will enable sms feature in the system</span>
										</div>
									</div>
						
								</div>
								<div class="card-footer">
									<div class="row">
										
										<div class="col-lg-12 text-center">
										<input type="hidden" name="setting_id" class="form-control" value="{{$settings->id}}">
											<button type="submit" class="btn btn-primary mr-2"><i class="fas fa-save"></i> Save</button>
										</div>
									</div>
								</div>
							</form>
						</div>
						<hr>
						<!--begin::Header-->
						
						<div class="card-header border-0 py-5">
							<h3 class="card-title align-items-start flex-column">
								<span class="card-label font-weight-bolder text-dark">School Setting.</span>
								<span class="text-muted mt-3 font-weight-bold font-size-sm">ANHS-SOA School Setups.</span>
							</h3>
							
						</div>
						<!--end::Header-->
						<div class="card-body pt-0 pb-3">
						@if(session('success_attendance_setting'))
					        <div class="alert alert-success" role="alert">
					            {{ session('success_attendance_setting') }}     
					        </div>
					    @endif

							<form class="form" action="{{route('panel.admin.save_attendance_setup')}}" method="post">
								@csrf
								<div class="card-body">
								
									<div class="form-group row">
										<div class="col-lg-3">
											<label>School Name</label>
											<input type="text" name="school_name" class="form-control" value="{{$attendance_setups->school_name}}">
											<span class="form-text text-muted">School Name</span>
										</div>
										<div class="col-lg-3">
											<label>School ID</label>
											<input type="text" name="school_id" class="form-control" value="{{$attendance_setups->school_id}}">
											<span class="form-text text-muted">School ID</span>
										</div>
										<div class="col-lg-3">
											<label>District</label>
											<input type="text" name="district" class="form-control" value="{{$attendance_setups->district}}">
											<span class="form-text text-muted">District</span>
										</div>
										
										<div class="col-lg-3">
											<label>Division</label>
											<input type="text" name="division" class="form-control" value="{{$attendance_setups->division}}">
											<span class="form-text text-muted">Division</span>
										</div>
										
									</div>
									<div class="form-group row">
										<div class="col-lg-3">
											<label>Region</label>
											<input type="text" name="region" class="form-control" value="{{$attendance_setups->region}}">
											<span class="form-text text-muted">Region</span>
										</div>
										
									</div>
						
								</div>
								<div class="card-footer">
									<div class="row">
										
										<div class="col-lg-12 text-center">
										<input type="hidden" name="school_setting_id" class="form-control" value="{{$attendance_setups->id}}">
											<button type="submit" class="btn btn-primary mr-2"><i class="fas fa-save"></i> Save</button>
										</div>
									</div>
								</div>
							</form>
						</div>
						<!--end::Body-->
					</div>
					<!--end::Advance Table Widget 4-->
				</div>
			</div>
			<!--end::Row-->
			<!--end::Dashboard-->
		</div>
		<!--end::Container-->
	</div>
	<!--end::Entry-->
</div>
@endsection

resources/views/panel/admin/students-filter.blade.php
@extends('layouts.panel')
@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">				
	<!--begin::Entry-->
	<div class="d-flex flex-column-fluid">
		<!--begin::Container-->
		<div class="container">
			<!--begin::Dashboard-->
			
			<!--begin::Row-->
			<div class="row">
				<div class="col-lg-12">
					<!--begin::Advance Table Widget 4-->
					<div class="card card-custom card-stretch gutter-b">
						<!--begin::Header-->
						<div class="card-header border-0 py-5">
							<h3 class="card-title align-items-start flex-column">
								<span class="card-label font-weight-bolder text-dark">Students</span>
							</h3>
						</div>
						<!--end::Header-->
						<!--begin::Body-->
						<div class="card-body pt-0 pb-3">
                            <form class="no-print" action="{{route('panel.admin.filter_students')}}" method="post">
                                <div class="form-group row">
                                    @csrf
                                    <div class="col-lg-2">
                                        <label class="col-form-label">School Year</label>
                                        <select name="year" id="year" class="form-control form-control-solid">
                                           <option value="2021-2022">2021-2022</option>
                                           <option value="2022-2023">2022-2023</option>
                                           <option value="2023-2024">2023-2024</option>
                                           <option value="2024-2025">2024-2025</option>
                                        </select>
                                        <span class="form-text text-muted">Please select month</span>
                                    </div>
                                    <div class="col-lg-2">
                                        <label class="col-form-label">Semester</label>
                                        <select name="semester" id="semester" class="form-control form-control-solid">
                                            <option value="1st Semester">1st Semester</option>
                                            <option value="2nd Semester">2nd Semester</option>
                                            <option value="Summer">Summer</option>
                                        </select>
                                        <span class="form-text text-muted">Please select month</span>
                                    </div>
                                    <div class="col-lg-2 pt-11">
                                        <label class="col-form-label"> &nbsp;</label>
                                        <button type="submit" class="btn btn-primary"> Students</button>
                                    </div>
                                </div>
                            </form>
							<div class="tab-content">
								<!--begin::Table-->
								<div class="table-responsive">
                                    <h3>Results for {{$year}} | {{$semester}}</h3>
									<table class="table table-head-custom table-head-bg table-borderless table-vertical-center" >
										<thead>
											<tr class="text-left text-uppercase">
												<th style="">
													<span class="text-dark-75">ID #</span>
												</th>
												<th style="" class="pl-7">
													<span class="text-dark-75">Name</span>
												</th>
												<th>Parent Name</th>
                                                <th>Contact Number</th>
                        
												<th >Grade</th>
												<th >Section</th>
											</tr>
										</thead>
										<tbody id="studentTable">
											@foreach($students as $student)
											<tr class="row{{$student->id}}">
												<td>{{$student->student->id_number}}</td>
												<td class="py-8">
													<div class="d-flex align-items-center">
														<div>
															<strong>{{$student->student->first_name}} {{$student->student->last_name}}</strong>
														</div>
													</div>
												</td>
												<td>{{$student->student->parent_name}}</td>
												<td>{{$student->student->contact_number}}</td>
                                                <td>{{$student->student->grade_year}}</td>
                                                <td>{{$student->section_info->section}}</td>
											</tr>
											@endforeach
										</tbody>
									</table>
                                    <button class="btn btn-info no-print" onclick="window.print();"><i class="fas fa-print"></i>  Print</button>
								</div>
								<!--end::Table-->
							</div>
						</div>
						<!--end::Body-->
					</div>
					<!--end::Advance Table Widget 4-->
				</div>
			</div>
			<!--end::Row-->
			<!--end::Dashboard-->
		</div>
		<!--end::Container-->
	</div>
	<!--end::Entry-->
</div>

@endsection

@section('jslinks')
<script>
    $(document).ready(function () {
        $("#grade").change(function () {
			console.log('Clicked!');
            var value=$(this).val();
            $.ajax({
                type : 'get',
                url : '{{route("panel.admin.students_search_section")}}',
                data:{'search':value},
                success:function(data){
                    //$("#loading_city_municipality").css("display", "block");
                    setTimeout(function(){
                        //$("#loading_city_municipality").css("display", "none");
                        //$("#municipality").css("display", "block");
                        $('#section').find('option').remove().end();
                        $('#section').append(data);
                    },500);
                } 
            });
        });

    });
</script>
<script src="{{asset('js/students.js')}}"></script>
<script src="{{asset('js/app.js')}}"></script>  
@endsection